### ISSUE TITLE
Neovim Tailwind CSS Plugin

### ISSUE THREAD

**Issue by roobert** [harrisoncramer/nvim#5]
Hi Harrison,

I took some code from your nvim config and packaged it into a plugin, here: https://github.com/roobert/tailwindcss-colorizer.nvim

Happy for you to clone and maintain this and I'll delete my copy if you'd like since this is not my original work.

Either way, it'd be good to submit this to neovim weekly once it's found a home as I'm sure others would find it useful!

Cheers

Rob

**Comment by harrisoncramer** [comment]
Hey Rob,

Actually believe that I pulled that from <a href="https://github.com/kabouzeid/dotfiles">Kabouzeid's dotfiles</a> originally! He wrote about it on Reddit a while ago: https://www.reddit.com/r/neovim/comments/mi9wli/got_tailwindcss_color_highlighting_working/

He doesn't seem to be using it anymore, I'm not seeing it in his Neovim configuration (good thing that I pulled it out I guess). I'm not really interested in maintaining this plugin, so you're welcome to take it over if you want, since you packaged it up. In any case I'd definitely post a comment in Reddit so folks know about it. Think that original thread is archived sadly.

**Comment by roobert** [comment]
Ah ok, thanks Harrison! I'll see what I can do.

I wrote this today, which you might be interested in: https://github.com/roobert/tailwindcss-colorizer-cmp.nvim

I'd like to chain how formatting works for cmp which I'll try to work out how to do soon but other than that this seems to work pretty nicely.
